use super::ice;
use crate::api::streaming::rtc::peer::FeedbackPeer as RTCPeerConnection;
use anyhow::{Context, Result};
use bytes::BytesMut;
use rtc::sansio::Protocol;
use rtc::shared::{TaggedBytesMut, TransportContext, TransportProtocol};
use std::net::{SocketAddr, UdpSocket as StdUdpSocket};
use std::sync::atomic::Ordering;
use std::sync::mpsc::{self, Receiver, TryRecvError};
use std::thread;
use std::time::{Duration, Instant};
use tokio::net::UdpSocket;

/// A datagram captured by the dedicated receive thread together with its true
/// wire-arrival instant.
struct CapturedDatagram {
    data: Vec<u8>,
    peer_addr: SocketAddr,
    at: Instant,
}

/// UDP/ICE transport shared by WebRTC streaming providers.
pub(crate) struct RtcTransport {
    pub(crate) socket: UdpSocket,
    local_addr: SocketAddr,
    datagrams: Receiver<CapturedDatagram>,
}

impl RtcTransport {
    pub(crate) async fn bind(
        peer: &mut RTCPeerConnection,
        stun_server: &str,
        route_probe: &str,
    ) -> Result<Self> {
        let std_socket = StdUdpSocket::bind("0.0.0.0:0")
            .context("failed to bind UDP socket for WebRTC transport")?;
        std_socket
            .set_nonblocking(true)
            .context("failed to set UDP socket non-blocking")?;
        let socket_addr = std_socket
            .local_addr()
            .context("failed to read local UDP socket address")?;
        let local_addr = ice::add_host_candidate(peer, socket_addr.port(), route_probe)
            .context("failed to add local host ICE candidate")?;

        // Dedicated RX thread: drains the kernel buffer within ~1 ms regardless of
        // render/presentation load on the UI thread (vita-moonlight-relay's fix for
        // "image lags behind while controls responsive"). The cloned fd shares the
        // O_NONBLOCK flag with the async twin on POSIX, so the thread polls with a
        // 1 ms sleep instead of blocking.
        let rx_socket = std_socket
            .try_clone()
            .context("failed to clone UDP socket for receive thread")?;
        let socket = UdpSocket::from_std(std_socket)
            .context("failed to register UDP socket with the async runtime")?;

        match ice::discover_server_reflexive_candidate(&socket, local_addr, stun_server).await {
            Ok(Some(public_addr)) => {
                if let Err(error) =
                    ice::add_srflx_candidate(peer, public_addr, local_addr, stun_server)
                {
                    eprintln!("Failed to add server-reflexive ICE candidate: {error:#}");
                }
            }
            Ok(None) => eprintln!("STUN request produced no usable response"),
            Err(error) => eprintln!("STUN discovery failed: {error:#}"),
        }

        ice::local_candidate(peer, String::new(), None)
            .context("failed to signal end-of-candidates")?;

        let (tx, datagrams) = mpsc::sync_channel::<CapturedDatagram>(2048);
        thread::Builder::new()
            .name("rtc-recv".into())
            .spawn(move || {
                // Pin RX to its own core so render/GUI load on the main thread
                // cannot delay datagram pickup; main thread pins itself to core 0.
                unsafe {
                    let result = vitasdk_sys::sceKernelChangeThreadCpuAffinityMask(
                        vitasdk_sys::SCE_KERNEL_THREAD_ID_SELF as _,
                        0b0010,
                    );
                    if result != 0 {
                        eprintln!("rtc-recv affinity pin failed: {result}");
                    }
                }
                let mut buf = vec![0u8; 2048];
                loop {
                    match rx_socket.recv_from(&mut buf) {
                        Ok((n, peer_addr)) => {
                            let datagram = CapturedDatagram {
                                data: buf[..n].to_vec(),
                                peer_addr,
                                at: Instant::now(),
                            };
                            if tx.send(datagram).is_err() {
                                break;
                            }
                        }
                        Err(error) if error.kind() == std::io::ErrorKind::WouldBlock => {
                            thread::sleep(Duration::from_millis(1));
                        }
                        Err(error) => {
                            eprintln!("WebRTC receive thread stopped: {error}");
                            break;
                        }
                    }
                }
            })
            .context("failed to spawn WebRTC receive thread")?;

        Ok(Self {
            socket,
            local_addr,
            datagrams,
        })
    }

    pub(crate) async fn flush(&self, peer: &mut RTCPeerConnection) {
        while let Some(outgoing) = peer.poll_write() {
            // TWCC feedback (RTPFB, PT=205, FMT=15) is generated by the interceptor
            // chain; counting at the socket proves it actually leaves the client.
            let bytes = &outgoing.message;
            if bytes.len() >= 2 && bytes[1] == 205 && bytes[0] & 0x1F == 15 {
                crate::streaming::video::metrics::METRICS
                    .twcc_sent
                    .fetch_add(1, Ordering::Relaxed);
            }
            if let Err(error) = self
                .socket
                .send_to(&outgoing.message, outgoing.transport.peer_addr)
                .await
            {
                eprintln!(
                    "Failed to send WebRTC UDP packet to {}: {error}",
                    outgoing.transport.peer_addr
                );
            }
        }
    }

    pub(crate) fn receive(&mut self, peer: &mut RTCPeerConnection) {
        loop {
            match self.datagrams.try_recv() {
                Ok(datagram) => {
                    if let Err(error) = peer.handle_read(TaggedBytesMut {
                        now: datagram.at,
                        transport: TransportContext {
                            local_addr: self.local_addr,
                            peer_addr: datagram.peer_addr,
                            ecn: None,
                            transport_protocol: TransportProtocol::UDP,
                        },
                        message: BytesMut::from(datagram.data.as_slice()),
                    }) {
                        eprintln!(
                            "Failed to handle WebRTC UDP packet from {}: {error}",
                            datagram.peer_addr
                        );
                    }
                }
                Err(TryRecvError::Empty) => break,
                Err(TryRecvError::Disconnected) => {
                    eprintln!("WebRTC receive channel closed");
                    break;
                }
            }
        }
    }
}
